[package]
name = "lpi-lexer"
description = "Applesoft II BASIC lexer"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
winnow = { workspace = true }
